// beginner to intermediate icons
export const begToIntIcons = [
  {
    name: "HTML5",
    src: "svg/html5.svg",
    alt: "HTML5 icon",
    title: "HTML5 icon",
    className: "tech-icons",
  },
  {
    name: "CSS3",
    src: "svg/css3.svg",
    alt: "CSS3 icon",
    title: "CSS3 icon",
    className: "tech-icons",
  },
  {
    name: "JavaScript",
    src: "svg/js.svg",
    alt: "JavaScript icon",
    title: "JavaScript icon",
    className: "tech-icons",
  },
  {
    name: "React",
    src: "icons/react.png",
    alt: "React icon",
    title: "React icon",
    className: "tech-icons",
  },
  {
    name: "SaSS",
    src: "svg/sass.svg",
    alt: "SASS icon",
    title: "SASS icon",
    className: "tech-icons",
  },
  {
    name: "Node JS",
    src: "svg/nodejs.svg",
    alt: "Node JS icon",
    title: "Node JS icon",
    className: "tech-icons",
  },
  {
    name: "Express JS",
    src: "svg/express.svg",
    alt: "Express icon",
    title: "Express icon",
    className: "tech-icons",
  },
  {
    name: "Socket.io",
    src: "svg/socket-io.svg",
    alt: "Socket.io icon",
    title: "Socket.io icon",
    className: "tech-icons",
  },
  {
    name: "Adobe Illustrator",
    src: "svg/illustrator.svg",
    alt: "Illustrator icon",
    title: "Illustrator icon",
    className: "tech-icons",
  },
];
// intermediate to advanced icons
export const intToAdvIcons = [
  {
    name: "JavaScript",
    src: "svg/js.svg",
    alt: "JavaScript icon",
    title: "JavaScript icon",
    className: "tech-icons",
  },
  {
    name: "React",
    src: "icons/react.png",
    alt: "React icon",
    title: "React icon",
    className: "tech-icons",
  },
  {
    name: "Node JS",
    src: "svg/nodejs.svg",
    alt: "Node JS icon",
    title: "Node JS icon",
    className: "tech-icons",
  },
  {
    name: "Express JS",
    src: "svg/express.svg",
    alt: "Express icon",
    title: "Express icon",
    className: "tech-icons",
  },
  {
    name: "Socket.io",
    src: "svg/socket-io.svg",
    alt: "Socket.io icon",
    title: "Socket.io icon",
    className: "tech-icons",
  },
  {
    name: "Parcel",
    src: "svg/parcel.svg",
    alt: "Parcel icon",
    title: "Parcel icon",
    className: "tech-icons",
  },
];
